name: Update CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: native

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate datas
        run: nix run

      - name: Commit + Push changes
        run: |
          printf "Setting git + tracking changes"
          git config --global user.name "Uzinfocom Asssistant"
          git config --global user.email "support@oss.uzinfocom.uz"
          git add .

          if [ -n "$(git status --porcelain)" ]; then
            printf "Commiting changes to branch"
            git commit -m "Update databases ${{ github.event.repository.updated_at}}"

            printf "Replacing origin upstream"
            git remote rm origin
            git remote add origin "https://support:${{ secrets.PAT }}@git.oss.uzinfocom.uz/xinux/monitor.git"

            printf "Pushing changes to upstream"
            git push --set-upstream origin main
          else
            echo "No changes detected, exiting..." && exit 0;
          fi
