#!/bin/bash

set -euxo pipefail

remote=https://github.com/nixos/nixpkgs.git
gitcache="$HOME/.cache/git-cache"
(
  mkdir -p "$gitcache"
  cd "$gitcache" || exit 1
  if [ ! -d ./nixpkgs ]; then
    git clone "$remote" ./nixpkgs
  fi

  cd nixpkgs || exit 1
  git remote set-url origin "$remote"
  git gc
  git fetch "origin"
)

if [ ! -d ./nixpkgs ]; then
  git clone --reference "$gitcache/nixpkgs" -- "$remote" ./nixpkgs
fi

calculate "$PWD/nixpkgs" "./data"

make-index ./data

git add ./data
