name: "Update and deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/flakehub-cache-action@main

    - name: Create databases
      run: |
        nix build
        ./result/bin/calculate-and-push

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update databases
        commit_user_email: developers@floss.uz
        commit_author: GitHub Actions <developers@floss.uz>

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './data'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
